# Generated by Django 3.1 on 2020-09-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('image', models.ImageField(upload_to='recetas', verbose_name='Imagen')),
                ('ingredients', models.TextField(verbose_name='Ingredientes')),
                ('preparation', models.TextField(verbose_name='Preparacíon')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Edición')),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
                'ordering': ['created'],
            },
        ),
    ]
