# Generated by Django 3.1 on 2020-09-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_recetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='image',
        ),
    ]
