# Generated by Django 3.1 on 2020-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_recetas', '0003_receta_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
    ]
