# Generated by Django 3.1 on 2020-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_recetas', '0004_receta_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='image',
        ),
        migrations.AlterField(
            model_name='receta',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo'),
        ),
    ]
