# Generated by Django 3.1 on 2020-10-08 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_recetas', '0006_receta_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=50, verbose_name='Título')),
                ('likes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Subtitulo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Edición')),
                ('receta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_recetas.receta')),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
                'ordering': ['created'],
            },
        ),
    ]
