# Generated by Django 3.1 on 2020-10-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_recetas', '0007_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='mensaje',
            field=models.CharField(max_length=300, verbose_name='Título'),
        ),
    ]
