# Generated by Django 3.1 on 2020-10-08 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_recetas', '0008_auto_20201007_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='comentario',
            name='message',
            field=models.CharField(default=0, max_length=300, verbose_name='Mensaje'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='receta_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App_recetas.receta'),
        ),
    ]
